-- =============================================
-- Taka Bachai - Database Schema
-- Personal Money Management System
-- =============================================

-- Drop legacy views first so CREATE OR REPLACE always works on a clean state
DROP VIEW IF EXISTS vw_user_financial_summary; -- MySQL: DROP VIEW IF EXISTS vw_user_financial_summary;
DROP VIEW IF EXISTS vw_spending_insights; -- MySQL: DROP VIEW IF EXISTS vw_spending_insights;

-- ---------------- USERS ----------------
CREATE TABLE IF NOT EXISTS users ( -- MySQL: CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- MySQL: id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    full_name   VARCHAR(100) NOT NULL, -- MySQL: full_name   VARCHAR(100) NOT NULL,
    email       VARCHAR(150) UNIQUE NOT NULL, -- MySQL: email       VARCHAR(150) UNIQUE NOT NULL,
    phone       VARCHAR(20), -- MySQL: phone       VARCHAR(20),
    role        VARCHAR(20) DEFAULT 'USER', -- MySQL: role        VARCHAR(20) DEFAULT 'USER',
    created_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP -- MySQL: created_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
); -- MySQL: );

-- ---------------- WALLETS ----------------
CREATE TABLE IF NOT EXISTS wallets ( -- MySQL: CREATE TABLE IF NOT EXISTS wallets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- MySQL: id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, -- MySQL: user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    wallet_name VARCHAR(50)  NOT NULL, -- MySQL: wallet_name VARCHAR(50)  NOT NULL,
    -- CASH, BKASH, NAGAD, BANK, ROCKET, CREDIT_CARD
    wallet_type VARCHAR(30)  NOT NULL, -- MySQL: wallet_type VARCHAR(30)  NOT NULL,
    balance     DECIMAL(15,2) NOT NULL DEFAULT 0.00, -- MySQL: balance     DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    currency    VARCHAR(5)   NOT NULL DEFAULT 'BDT', -- MySQL: currency    VARCHAR(5)   NOT NULL DEFAULT 'BDT',
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP -- MySQL: created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
); -- MySQL: );

-- ---------------- CATEGORIES ----------------
CREATE TABLE IF NOT EXISTS categories ( -- MySQL: CREATE TABLE IF NOT EXISTS categories (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- MySQL: id    BIGINT AUTO_INCREMENT PRIMARY KEY,
    name  VARCHAR(50) NOT NULL, -- MySQL: name  VARCHAR(50) NOT NULL,
    -- INCOME or EXPENSE
    type  VARCHAR(10) NOT NULL, -- MySQL: type  VARCHAR(10) NOT NULL,
    icon  VARCHAR(50), -- MySQL: icon  VARCHAR(50),
    color VARCHAR(10) -- MySQL: color VARCHAR(10)
); -- MySQL: );

-- ---------------- TRANSACTIONS ----------------
CREATE TABLE IF NOT EXISTS transactions ( -- MySQL: CREATE TABLE IF NOT EXISTS transactions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- MySQL: id               BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id          BIGINT NOT NULL REFERENCES users(id)    ON DELETE CASCADE, -- MySQL: user_id          BIGINT NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
    wallet_id        BIGINT NOT NULL REFERENCES wallets(id)  ON DELETE CASCADE, -- MySQL: wallet_id        BIGINT NOT NULL REFERENCES wallets(id)  ON DELETE CASCADE,
    category_id      BIGINT          REFERENCES categories(id) ON DELETE SET NULL, -- MySQL: category_id      BIGINT          REFERENCES categories(id) ON DELETE SET NULL,
    type             VARCHAR(10)  NOT NULL, -- MySQL: type             VARCHAR(10)  NOT NULL,
    amount           DECIMAL(15,2) NOT NULL CHECK (amount > 0), -- MySQL: amount           DECIMAL(15,2) NOT NULL CHECK (amount > 0),
    description      VARCHAR(255), -- MySQL: description      VARCHAR(255),
    transaction_date TIMESTAMP    NOT NULL, -- MySQL: transaction_date TIMESTAMP    NOT NULL,
    receipt_path     VARCHAR(500), -- MySQL: receipt_path     VARCHAR(500),
    created_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP -- MySQL: created_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
); -- MySQL: );

-- ---------------- BUDGETS ----------------
CREATE TABLE IF NOT EXISTS budgets ( -- MySQL: CREATE TABLE IF NOT EXISTS budgets (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- MySQL: id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id)      ON DELETE CASCADE, -- MySQL: user_id      BIGINT NOT NULL REFERENCES users(id)      ON DELETE CASCADE,
    category_id  BIGINT          REFERENCES categories(id) ON DELETE CASCADE, -- MySQL: category_id  BIGINT          REFERENCES categories(id) ON DELETE CASCADE,
    -- YYYY-MM
    budget_month VARCHAR(7)    NOT NULL, -- MySQL: budget_month VARCHAR(7)    NOT NULL,
    limit_amount DECIMAL(15,2) NOT NULL CHECK (limit_amount > 0), -- MySQL: limit_amount DECIMAL(15,2) NOT NULL CHECK (limit_amount > 0),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- MySQL: created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, category_id, budget_month) -- MySQL: UNIQUE (user_id, category_id, budget_month)
); -- MySQL: );

-- ---------------- RECURRING BILLS ----------------
CREATE TABLE IF NOT EXISTS recurring_bills ( -- MySQL: CREATE TABLE IF NOT EXISTS recurring_bills (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- MySQL: id            BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users(id)      ON DELETE CASCADE, -- MySQL: user_id       BIGINT NOT NULL REFERENCES users(id)      ON DELETE CASCADE,
    wallet_id     BIGINT          REFERENCES wallets(id)    ON DELETE SET NULL, -- MySQL: wallet_id     BIGINT          REFERENCES wallets(id)    ON DELETE SET NULL,
    category_id   BIGINT          REFERENCES categories(id) ON DELETE SET NULL, -- MySQL: category_id   BIGINT          REFERENCES categories(id) ON DELETE SET NULL,
    bill_name     VARCHAR(100)  NOT NULL, -- MySQL: bill_name     VARCHAR(100)  NOT NULL,
    amount        DECIMAL(15,2) NOT NULL CHECK (amount > 0), -- MySQL: amount        DECIMAL(15,2) NOT NULL CHECK (amount > 0),
    -- DAILY, WEEKLY, MONTHLY, YEARLY
    frequency     VARCHAR(20)   NOT NULL, -- MySQL: frequency     VARCHAR(20)   NOT NULL,
    next_due_date DATE          NOT NULL, -- MySQL: next_due_date DATE          NOT NULL,
    is_active     BOOLEAN       NOT NULL DEFAULT TRUE, -- MySQL: is_active     TINYINT(1)       NOT NULL DEFAULT 1,
    created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP -- MySQL: created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
); -- MySQL: );

-- ---------------- FINANCIAL GOALS ----------------
CREATE TABLE IF NOT EXISTS financial_goals ( -- MySQL: CREATE TABLE IF NOT EXISTS financial_goals (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- MySQL: id             BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, -- MySQL: user_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    goal_name      VARCHAR(100)  NOT NULL, -- MySQL: goal_name      VARCHAR(100)  NOT NULL,
    target_amount  DECIMAL(15,2) NOT NULL CHECK (target_amount > 0), -- MySQL: target_amount  DECIMAL(15,2) NOT NULL CHECK (target_amount > 0),
    current_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00 CHECK (current_amount >= 0), -- MySQL: current_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00 CHECK (current_amount >= 0),
    deadline       DATE, -- MySQL: deadline       DATE,
    -- IN_PROGRESS, COMPLETED, CANCELLED
    status         VARCHAR(20)   NOT NULL DEFAULT 'IN_PROGRESS', -- MySQL: status         VARCHAR(20)   NOT NULL DEFAULT 'IN_PROGRESS',
    created_at     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP -- MySQL: created_at     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
); -- MySQL: );

-- ---------------- DEBTS / LOANS ----------------
CREATE TABLE IF NOT EXISTS debts_loans ( -- MySQL: CREATE TABLE IF NOT EXISTS debts_loans (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- MySQL: id               BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id          BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, -- MySQL: user_id          BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- DEBT (I owe) or LOAN (owed to me)
    type             VARCHAR(10)   NOT NULL, -- MySQL: type             VARCHAR(10)   NOT NULL,
    person_name      VARCHAR(100)  NOT NULL, -- MySQL: person_name      VARCHAR(100)  NOT NULL,
    amount           DECIMAL(15,2) NOT NULL CHECK (amount > 0), -- MySQL: amount           DECIMAL(15,2) NOT NULL CHECK (amount > 0),
    remaining_amount DECIMAL(15,2) NOT NULL CHECK (remaining_amount >= 0), -- MySQL: remaining_amount DECIMAL(15,2) NOT NULL CHECK (remaining_amount >= 0),
    description      VARCHAR(255), -- MySQL: description      VARCHAR(255),
    due_date         DATE, -- MySQL: due_date         DATE,
    -- PENDING, PARTIALLY_PAID, PAID
    status           VARCHAR(20)   NOT NULL DEFAULT 'PENDING', -- MySQL: status           VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    created_at       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP -- MySQL: created_at       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
); -- MySQL: );

-- ---------------- INDEXES ----------------
CREATE INDEX IF NOT EXISTS idx_transactions_user       ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_wallet     ON transactions(wallet_id);
CREATE INDEX IF NOT EXISTS idx_transactions_date       ON transactions(transaction_date);
CREATE INDEX IF NOT EXISTS idx_transactions_type       ON transactions(type);
CREATE INDEX IF NOT EXISTS idx_transactions_category   ON transactions(category_id);
CREATE INDEX IF NOT EXISTS idx_wallets_user            ON wallets(user_id);
CREATE INDEX IF NOT EXISTS idx_budgets_user_month      ON budgets(user_id, budget_month);
CREATE INDEX IF NOT EXISTS idx_budgets_category        ON budgets(category_id);
CREATE INDEX IF NOT EXISTS idx_recurring_bills_user    ON recurring_bills(user_id);
CREATE INDEX IF NOT EXISTS idx_recurring_bills_wallet  ON recurring_bills(wallet_id);
CREATE INDEX IF NOT EXISTS idx_recurring_bills_category ON recurring_bills(category_id);
CREATE INDEX IF NOT EXISTS idx_financial_goals_user    ON financial_goals(user_id);
CREATE INDEX IF NOT EXISTS idx_debts_loans_user        ON debts_loans(user_id);

-- =========================================================================
-- COMPLEX SQL QUERIES (COURSE REQUIREMENTS)
-- =========================================================================

-- -------------------------------------------------------------------------
-- 1. OUTER JOIN & SUBQUERIES
-- Feature: Advanced Admin Financial Summary
-- -------------------------------------------------------------------------
-- For every user, calculates the total wallet balance and total *outstanding*
-- DEBT (only `type = 'DEBT'` and only the not-yet-repaid `remaining_amount`).
-- Uses LEFT OUTER JOINs against nested aggregate subqueries so users with no
-- wallets/debts still appear and to avoid Cartesian products when a user has
-- multiple wallets and debts simultaneously.
CREATE OR REPLACE VIEW vw_user_financial_summary AS -- MySQL: CREATE OR REPLACE VIEW vw_user_financial_summary AS
SELECT -- MySQL: SELECT
    u.id, -- MySQL: u.id,
    u.full_name, -- MySQL: u.full_name,
    u.email, -- MySQL: u.email,
    u.role, -- MySQL: u.role,
    COALESCE(w_agg.total_balance, 0) AS total_balance, -- MySQL: COALESCE(w_agg.total_balance, 0) AS total_balance,
    COALESCE(d_agg.total_debt,    0) AS total_debt -- MySQL: COALESCE(d_agg.total_debt,    0) AS total_debt
FROM users u -- MySQL: FROM users u
LEFT OUTER JOIN ( -- MySQL: LEFT OUTER JOIN (
    SELECT user_id, SUM(balance) AS total_balance -- MySQL: SELECT user_id, SUM(balance) AS total_balance
    FROM wallets -- MySQL: FROM wallets
    GROUP BY user_id -- MySQL: GROUP BY user_id
) w_agg ON u.id = w_agg.user_id -- MySQL: ) w_agg ON u.id = w_agg.user_id
LEFT OUTER JOIN ( -- MySQL: LEFT OUTER JOIN (
    SELECT user_id, SUM(remaining_amount) AS total_debt -- MySQL: SELECT user_id, SUM(remaining_amount) AS total_debt
    FROM debts_loans -- MySQL: FROM debts_loans
    WHERE type = 'DEBT' AND status <> 'PAID' -- MySQL: WHERE type = 'DEBT' AND status <> 'PAID'
    GROUP BY user_id -- MySQL: GROUP BY user_id
) d_agg ON u.id = d_agg.user_id; -- MySQL: ) d_agg ON u.id = d_agg.user_id;

-- -------------------------------------------------------------------------
-- 2. INNER JOIN & NESTED SUBQUERIES (HAVING clause)
-- Feature: Spending Insights vs Platform Average
-- -------------------------------------------------------------------------
-- For each user, returns categories where they spent more than the platform
-- average for that category. INNER JOINs `transactions` with `categories`,
-- then nests subqueries in SELECT and HAVING to compute the dynamic platform
-- average on the fly.
CREATE OR REPLACE VIEW vw_spending_insights AS -- MySQL: CREATE OR REPLACE VIEW vw_spending_insights AS
SELECT -- MySQL: SELECT
    t.user_id, -- MySQL: t.user_id,
    c.name              AS category_name, -- MySQL: c.name              AS category_name,
    SUM(t.amount)       AS user_spending, -- MySQL: SUM(t.amount)       AS user_spending,
    ca.average_spending AS average_spending -- MySQL: ca.average_spending AS average_spending
FROM transactions t -- MySQL: FROM transactions t
INNER JOIN categories c ON t.category_id = c.id -- MySQL: INNER JOIN categories c ON t.category_id = c.id
INNER JOIN ( -- MySQL: INNER JOIN (
    SELECT category_id, AVG(total_spent) AS average_spending -- MySQL: SELECT category_id, AVG(total_spent) AS average_spending
    FROM ( -- MySQL: FROM (
        SELECT user_id, category_id, SUM(amount) AS total_spent -- MySQL: SELECT user_id, category_id, SUM(amount) AS total_spent
        FROM transactions -- MySQL: FROM transactions
        WHERE type = 'EXPENSE' -- MySQL: WHERE type = 'EXPENSE'
        GROUP BY user_id, category_id -- MySQL: GROUP BY user_id, category_id
    ) AS user_totals -- MySQL: ) AS user_totals
    GROUP BY category_id -- MySQL: GROUP BY category_id
) ca ON c.id = ca.category_id -- MySQL: ) ca ON c.id = ca.category_id
WHERE t.type = 'EXPENSE' -- MySQL: WHERE t.type = 'EXPENSE'
GROUP BY t.user_id, c.id, c.name, ca.average_spending -- MySQL: GROUP BY t.user_id, c.id, c.name, ca.average_spending
HAVING SUM(t.amount) > ca.average_spending; -- MySQL: HAVING SUM(t.amount) > ca.average_spending;
